[#prerequisites]
=== Prerequisites

Each algorithm implementation *MAY* rely on other cryptographic primitives.	For example, XXXXXX. Each of these underlying algorithm primitives must be validated, either separately or as part of the same submission. ACVP provides a mechanism for specifying the required prerequisites:

Prerequisites, if applicable, *MUST* be submitted in the registration as the `prereqVals` JSON property array inside each element of the `algorithms` array. Each element in the `prereqVals` array *MUST* contain the following properties

|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | a prerequisite algorithm | string | XXX
| valValue | algorithm validation number | string | XXX
|===

A "valValue" of "same" *SHALL* be used to indicate that the prerequisite is being met by a different algorithm in the capability exchange in the same registration.

An example description of prerequisites within a single algorithm capability exchange looks like this

[source,json]
----
"prereqVals":
[
  {
    "algorithm": "Alg1",
    "valValue": "Val-1234"
  },
  {
    "algorithm": "Alg2",
    "valValue": "same"
  }
]
----
