
[[tgjs]]
=== Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups.  Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. The Test Group JSON object contains meta data that applies to all test vectors within the group.  The following table describes the RSA JSON elements of the Test Group JSON object.


[[vs_tg_table]]

[cols="<,<,<,<"]
. Test Group JSON Object
|===
| JSON Value| Description| JSON type| Optional

| modulo| RSA modulus| value| No
| hashAlg| the hash algorithm| value| Yes
| primeTest| Miller-Rabin constraint from Table C.2 or C.3| value| Yes
| pubExpMode| Fixed or random public exponent| "fixed" or "random"| Yes
| randPQ| KeyGen mode used| "B.3.2", "B.3.3", "B.3.4", "B.3.5", "B.3.6"| Yes
| fixedPubExp| Fixed public exponent value if pubExpMode is defined as "fixed"| hex value| Yes
| n | Public modulus value n | hex value| Yes
| e | Public exponent value e | hex value| Yes
| pubExpMode| Fixed or random public exponent| "fixed" or "random"| Yes
| sigType| Type of signature used in the group| "ansx9.31", "pkcs1v1.5", "pss"| Yes
| saltLen| The salt length for the group in bytes| value| Yes
| conformance| Signifies all test cases within the group should utilize random message hashing as described in <<SP800-106>>.| "SP800-106"| Yes
|===



[[tvjs]]
=== Test Case JSON Schema

Each test group contains an array of one or more test cases.  Each test case is a JSON object that represents a single test vector to be processed by the ACVP client.  The following table describes the JSON elements for each RSA test vector.



[[vs_tc_table]]

[cols="<,<,<,<"]
. RSA Test Case JSON Object
|===
| JSON Value| Description| JSON type| Optional

| tcId| Numeric identifier for the test case, unique across the entire vector set.| value| No
| e | the public exponent| hex value| Yes
| d | the private exponent| hex value| Yes
| n | the public modulus| hex value| Yes
| pRand| the random for P, testing probable primes according to
                        <<FIPS186-4>>, Appendix B.3.3
                    | hex value| Yes
| qRand| the random for Q, if applicable, testing probable primes according to
                        <<FIPS186-4>>, Appendix B.3.3
                    | hex value| Yes
| message| the message to be signed| hex value| Yes
| randomValue| The random value to be used as an input into the message randomization function as described in <<SP800-106>>.| value| Yes
| randomValueLen| The random value's bit length.| value| Yes
| signature| the signature to be verified| hex value| Yes
| cipherText| the cipherText to be decrypted| hex value| Yes
| cipherText| the cipherText to be decrypted| hex value| Yes
| salt| the salt value used to sign the message| hex value| Yes
|===

=== Test Groups for keyGen v1.0 and FIPS186-5

The testGroups element at the top level in the test vector JSON object is an array of test  groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {spec-algorithm} JSON elements of the Test Group JSON object

|===
| JSON Value | Description| JSON Type

| tgId | Test group identifier | integer
| modulo | RSA modulus | integer
| hashAlg | The hash algorithm | string
| primeTest | Miller-Rabin constraint defining the number of iterations to use | string
| randPQ | KeyGen mode used | string
| infoGeneratedByServer | Whether or not the test inputs are generated by the server | boolean
| keyFormat | The RSA private key format used | string
| pubExp | Fixed or random public exponent e | string
| testType | Describes the operation the client should perform on the test data | string
| tests | Array of individual test cases | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' (see <<testtypes>>) the group is addressing.

=== Test Cases for keyGen v1.0 and FIPS186-5

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each {spec-algorithm} test vector.

The difference between revision "v1.0" and "FIPS186-5" within the prompts lies in the strings used by the server to refer to the various "randPQ", and "primeTest" modes. Revision "v1.0" utilizes the section number from <<FIPS186-4>> to refer to the algorithm used while revision "FIPS186-5" utilizes a description of the algorithm.

|===
| JSON Value | Description | JSON Type

| tcId | Test case identifier | integer
| e | the public exponent | hex
| seed | the seed used in prime generation | hex
| bitlens | the length of p1, p2, q1, and q2 for prime generation | array of integers
| xP1 | the prime factor p1 for probable auxiliary primes | hex
| xP2 | the prime factor p2 for probable auxiliary primes | hex
| xP | the random number used in auxiliary prime generation for p | hex
| xQ1 | the prime factor q1 for probable auxiliary primes | hex
| xQ2 | the prime factor q2 for probable auxiliary primes | hex
| xQ | the random number used in auxiliary prime generation for q | hex
| pRand | the random P for testing probable primes according to <<FIPS186-4>> or <<FIPS186-5>> | hex
| qRand | the random Q for testing probable primes according to <<FIPS186-4>> or <<FIPS186-5>> | hex
|===

Here is an abbreviated yet fully constructed example of the prompt

----
{
  "vsId": 2,
  "algorithm": "RSA",
  "mode": "KeyGen",
  "revision": "FIPS186-5",
  "testGroups": [
    {
      "tgId": 1,
      "infoGeneratedByServer": true,
      "modulo": 2048,
      "testType": "AFT",
      "keyFormat": "crt",
      "randPQ": "provable",
      "pubExp": "random",
      "hashAlg": "SHA2-224",
      "tests": [
        {
          "tcId": 1,
          "seed": "5B174CA160...",
          "e": "07D196B84395"
        }
      ]
    },
    {
      "tgId": 3,
      "infoGeneratedByServer": true,
      "modulo": 2048,
      "testType": "AFT",
      "keyFormat": "crt",
      "primeTest": "2powSecStr",
      "randPQ": "probableWithProvableAux",
      "pubExp": "random",
      "tests": [
        {
          "tcId": 7,
          "seed": "B392CFFD8E...",
          "bitlens": [
            142,
            419,
            400,
            334
          ],
          "xp": "F06825A6B...",
          "xq": "BD106DBE5...",
          "e": "3691C632C2BBE7"
        }
      ]
    },
    {
      "tgId": 5,
      "infoGeneratedByServer": false,
      "modulo": 3072,
      "testType": "GDT",
      "keyFormat": "crt",
      "primeTest": "2pow100",
      "randPQ": "probable",
      "pubExp": "random",
      "tests": [
        {
          "tcId": 13
        }
      ]
    }
  ]
}
----
