[[app-reg-ex]]
== Example Capabilities JSON Object


[[app-reg-ex2]]
=== Example EDDSA Capabilities JSON Object

The following sections contain example JSON for the various EDDSA modes: keyGen, keyVer, sigGen, and sigVer. Note that all binary HEX representations are in big-endian byte order but little-endian bit format.

[align=left,alt=,type=]
....
                        
[{
		"algorithm": "EDDSA",
		"mode": "keyGen",
		"revision": "1.0",
		"prereqVals": [{
				"algorithm": "SHA",
				"valValue": "123456"
			},
			{
				"algorithm": "DRBG",
				"valValue": "123456"
			}
		],
		"curve": [
			"ED-25519",
			"ED-448"
		],
		"secretGenerationMode": [
			"extra bits",
			"testing candidates"
		]
	},
	{
		"algorithm": "EDDSA",
		"mode": "keyVer",
		"revision": "1.0",
		"prereqVals": [{
				"algorithm": "SHA",
				"valValue": "123456"
			},
			{
				"algorithm": "DRBG",
				"valValue": "123456"
			}
		],
		"curve": [
			"ED-25519",
			"ED-448"
		]
	},
	{
		"algorithm": "EDDSA",
		"mode": "sigGen",
		"revision": "1.0",
		"prereqVals": [{
				"algorithm": "SHA",
				"valValue": "123456"
			},
			{
				"algorithm": "DRBG",
				"valValue": "123456"
			}
		],
		"pure": true,
		"preHash": true,
		"curve": [
			"ED-25519",
			"ED-448"
		]
	},
	{
		"algorithm": "EDDSA",
		"mode": "sigVer",
		"revision": "1.0",
		"prereqVals": [{
				"algorithm": "SHA",
				"valValue": "123456"
			},
			{
				"algorithm": "DRBG",
				"valValue": "123456"
			}
		],
		"pure": true,
		"preHash": true,
		"curve": [
			"ED-25519",
			"ED-448"
		]
	}
]
            
                    
....



[[app-vs-ex]]
== Example Vector Set Request/Responses JSON Object


[[app-vs-ex5]]
=== Example Test EDDSA KeyGen JSON Object

The following is a example JSON object for EDDSA KeyGen, test vectors sent from the ACVP server to the crypto module and the response.

[align=left,alt=,type=]
....
                        
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "EDDSA",
        "mode": "keyGen",
        "revision": "1.0",
        "testGroups": [
            {
                "curve": "ED-25519",
                "secretGenerationMode": "extra bits",
				"testType": "AFT",
                "tests": [
                    {
                        "tcId": 1
                    }
                ]
            }
        ]
    }
]
            
                    
....


The following is a example JSON object for EDDSA KeyGen test results sent from the crypto module to the ACVP server.

[align=left,alt=,type=]
....
                        
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
				"tgId": 1,
				"tests": [
					{
						"tcId": 1,
						"q": "D51FB3D405A636227833A0950A2F4EDAF547F50448D7F371D0E9353F207B2B09",
						"d": "147BA261D11CD323331D87C22E215724E9CD5E6B6BEAC85A9808241D9E80781F"
					}
				]
            }
        ]
    }
]
            
                    
....



[[app-vs-ex6]]
=== Example Test EDDSA KeyVer JSON Object

The following is a example JSON object for EDDSA KeyVer, test vectors sent from the ACVP server to the crypto module and the response.

[align=left,alt=,type=]
....
                        
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "EDDSA",
        "mode": "keyVer",
        "revision": "1.0",
        "testGroups": [
            {
				"tgId": 1,
                "curve": "ED-25519",
				"testType": "AFT",
                "tests": [
                    {
                        "tcId": 1,
                        "q": "227093C50F7D04A41121CEFDF076CC8B21D44E7506F341F8BFAB269CE06F2B7E",
                    }
                ]
            }
        ]
    }
]
            
                    
....


The following is a example JSON object for EDDSA KeyVer test results sent from the crypto module to the ACVP server.

[align=left,alt=,type=]
....
                        
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
		"testGroups": [
			{
				"tgId": 1,
				"tests": [
					{
						"tcId": 1,
						"testPassed": true
					}
				]
            }
        ]
    }
]
            
                    
....



[[app-vs-ex8]]
=== Example Test EDDSA Signature Generation JSON Object

The following is a example JSON object for EDDSA SigGen, test vectors sent from the ACVP server to the crypto module and the response.

[align=left,alt=,type=]
....
                        
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "EDDSA",
        "mode": "sigGen",
        "revision": "1.0",
        "testGroups": [
            {
				"tgId": 1,
				"testType": "AFT",
                "curve": "ED-25519",
				"preHash": false,
                "tests": [
                    {
                        "tcId": 1,
                        "message": "A81C8A22735A260CB1A8105A2964646097D8A9B110701AB0D49C9071836CAD39E31F5020D24B2C841FAC58F44F3F3F814495B063A686F6F93C5C6D9FDF45B9099C609A69E6A9F6483C5038066A560D413C6FB73D76499A7D8836C9C89368D557B2C24A5D817CF1FBD226AC41037E3005250007B49C6CCCE7BD1BE5D7A5C96EE8"
                    }
                ]
            },
			{
				"tgId": 5,
				"testType": "bft",
				"curve": "ED-25519",
				"preHash": false,
				"tests": [
					{
						"tcId": 41,
						"message": "F27E9F9D"
					},
					{
						"tcId": 42,
						"message": "F27E9F9C"
					},
					{
						"tcId": 43,
						"message": "F27E9F9F"
					}
				]
			}
        ]
    }
]
            
                    
....


The following is a example JSON object for EDDSA SigGen test results sent from the crypto module to the ACVP server.

[align=left,alt=,type=]
....
                        
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
				"tgId": 1,
				"q": "4BA34FE699DBDC89750FF006AA35E282BF71C180B53C2DE620676C8707A14E48",
				"tests": [
					{
						"tcId": 1,
						"signature": "772990B0E53B3E21DC8BD139CECB39892D75BD70DAFFDC73E241E29515E67CC642CB2A6B479FFEF4F3F16B5BC3DDF06AB25A92028F2DC0464B3CFDFD3B8F4D08"
					}
				]
            },
			{
				"tgId": 5,
				"q": "ADD51513B67540E3A392721742C7E81F1BAE77DEFC16314E32A06976BA9BBFF7",
				"tests": [
					{
						"tcId": 41,
						"signature": "6EA857E68CEC0825EAD378A2F445BB17993D151CF9A168A44F47E13D356F6DC9AA67517DE4A2FB22BA24E1732DA0234427A2572CBE80294277F2141498E7F50E"
					},
					{
						"tcId": 42,
						"signature": "883B0336036509FC44CD2E507C5E916696213F9CF2429796E248516EFBDFAFE5C98EE6DBF82314B6FB5403383BC2E4ECCC89C7D686FE3A630B74866A0126740C"
					},
					{
						"tcId": 43,
						"signature": "E402705AC2EFC216EB7FA1AC5461A8451CE6F72B0AFA63D75BFBD5C4DD98A07207168CC6A542F01AAC6C31EC1C09062B053A54F6C93B801460FE33348B87DD03"
					}
				]
			}
        ]
    }
]
          
                    
....



[[app-vs-ex9]]
=== Example Test EDDSA SigVer JSON Object

The following is a example JSON object for EDDSA SigVer, test vectors sent from the ACVP server to the crypto module and the response.

[align=left,alt=,type=]
....
                        
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "EDDSA",
        "mode": "sigVer",
        "revision": "1.0",
        "testGroups": [
            {
				"tgId": 1,
				"testType": "AFT"
                "curve": "ED-25519",
                "preHash": false,
				"q": "502A28FAF736CBCF1B51A3816CADC61D6B46699149A442BA741B378386B7120C",
                "tests": [
                    {
                        "tcId": 1,
                        "message": "BED1D245D569D5C10693F408A195D0404D3F27DFD0C670034A99AFD5F33E84690812516F4335ED6B2D5FD824075B061D7BA5731DCA4EF01040167AC2D40320DEB7FC63A8B34CE5C05CF22EC0D7B11AC55C84D8131D3C656CBA05BB29F64A5D5C20AFD5212163A254B9915A30BBAB15FB3F710C325F408E8D1E840B55A09F52B7",
                        "signature": "9C09C0FF50B61E4443DBA5D1262B7CE6DDD3742BCAF288B0A17078F78ECB2480976448A177FFBB6E39FC9C02ABFA63806D664248C67803E4023A681E9930550F"
                    }
                ]
            }
        ]
    }
]
            
                    
....


The following is a example JSON object for EDDSA generation test results sent from the crypto module to the ACVP server.

[align=left,alt=,type=]
....
                        
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
				"tgId": 1,
				"tests": [
					{
                		"tcId": 1,
                		"testPassed": false
					}
				]
            }
        ]
    }
]
          
                    
....
