
[bibliography]
== Normative References

* [[[RFC2119,RFC 2119]]]
* [[[RFC3339,RFC 3339]]]
* [[[RFC3986,RFC 3986]]]
* [[[RFC5246,RFC 5246]]]
* [[[RFC7159,RFC 7159]]]
* [[[RFC7230,RFC 7230]]]
* [[[RFC7519,RFC 7519]]]
* [[[RFC7991,RFC 7991]]]
* [[[RFC8174,RFC 8174]]]

[bibliography]
== Informative References

[%bibitem]
=== ACVP IANA Registry
id:: acvp-iana
contributor::
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: NIST
date::
date.type:: published
date.value:: 2018-11-01

[%bibitem]
=== Cryptographic Algorithm Validation Program
id:: cavp
contributor::
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: NIST
date::
date.type:: published
date.value:: 2018-02

[%bibitem]
=== ACVP Symmetric Algorithm JSON Specification
id:: sub-symmetric
contributor::
contributor.person.name.initial:: C.
contributor.person.name.surname:: CELI
contributor.person.affiliation.organization.name:: NIST
date::
date.type:: published
date.value:: 2018
