
[#testtypes]
== Test Types and Test Coverage

This section describes the design of the tests used to validate {spec-algorithm} implementations.

=== Test Types

This section describes the design of the tests used to validate implementations of XOFs. There are three types of tests for these algorithms: Algorithm Functional Tests (AFT), Monte Carlo Tests (MCT) and MAC Verification Tests (MVT). Each has a specific value to be used in the testType field. The testType field definitions are:

* "AFT" - Algorithm Functional Tests. These tests can be processed by the client using a normal 'encrypt' or 'decrypt' operation. AFTs cause the implementation under test to exercise normal operations on a single block, multiple blocks, or (where applicable) partial blocks. In some cases random data is used, in others, static, predetermined tests are provided.

* "MCT" - Monte Carlo Tests. These tests exercise the implementation under test under strenuous circumstances. The implementation under test must process the test vectors according to the correct algorithm and mode in this document. MCTs can help detect potential memory leaks over time, and problems in allocation of resources, addressing variables, error handling and generally improper behavior in response to random inputs. Each MCT processes 100 pseudorandom tests. Not every algorithm and mode combination has an MCT. See <<MC_test>> for implementation details.

* "MVT" - MAC Verification Tests.  XXX

[[MC_test]]
=== Monte Carlo tests for XOFs

[[cSHAKE-MCT]]
==== cSHAKE Monte Carlo Test

[[ParallelHash-MCT]]
==== ParallelHash Monte Carlo Test

[[TupleHash-MCT]]
==== TupleHash Monte Carlo Test

=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-185>>.

[[xof-coverage]]
==== XOF Requirements Covered

In TBD.

[[xof-not-coverage]]
==== XOF Requirements Not Covered

Some requirements in the outlined specification are not easily tested. Often they are not ideal for black-box testing such as the ACVP. In TBD.
