
[appendix]
[[app-reg-ex]]
== Example SP800-135 TPM KDF Capabilities JSON Object

The following is a example JSON object advertising support for SHA-256.

[align=left,alt=,type=]
....
 
{
  "algorithm": "kdf-components",
  "mode": "tpm",
  "revision": "1.0",
  "prereqVals": [
    {
      "algorithm": "HMAC",
      "valValue": "123456"
    },
    {
      "algorithm": "SHA",
      "valValue": "123456"
    }
  ]
}
 
....



[appendix]
[[app-vs-ex]]
== Example Test Vectors JSON Object

The following is a example JSON object for SP800-135 TPM KDF test vectors sent from the ACVP server to the crypto module.

[align=left,alt=,type=]
....

[
  {
    "acvVersion": <acvp-version>
  },
  {
    "vsId": 1564,
    "algorithm": "kdf-components",
    "mode": "tpm",
    "revision": "1.0",
    "testGroups": [
      {
        "tgId": 1,
        "tests": [
          {
            "tcId": 2170,
            "auth": "fd771b263f6be051a1d7eb0c5138fbfcafbd49de",
            "nonceEven": "6b8790fd56b2b74734ea97db727ac9eb16e69831",
            "nonceOdd": "4fa48de2db65fa7082f4acc9f85ecc81d40d1793"
          }
        ]
      }
    ]
  }
]
                    
....


[appendix]
[[app-results-ex]]
== Example Test Results JSON Object

The following is a example JSON object for SP800-135 TPM KDF test results sent from the crypto module to the ACVP server.

[align=left,alt=,type=]
....

[
  {
    "acvVersion": "1.0"
  },
  {
    "vsId": 1564,
    "testGroups": [
      {
        "tgId": 1,
        "tests": [
          {
            "tcId": 2170,
            "sKey": "c431a158b7b77d7e993515f8ebc2cd6add53b702"
          }
        ]
      }
    ]
  }
]
                    
....


